// Auto-generated by file split — part of the D&D 5e Character Sheet project
// Edit this file directly to add or modify weapon and equipment reference data.

const WEAPONS = {
  'Club': {dmg:'1d4', type:'bludgeoning'},
  'Dagger': {dmg:'1d4', type:'piercing', finesse:true},
  'Greatclub': {dmg:'1d8', type:'bludgeoning'},
  'Handaxe': {dmg:'1d6', type:'slashing'},
  'Javelin': {dmg:'1d6', type:'piercing'},
  "Light Hammer": {dmg:'1d4', type:'bludgeoning'},
  'Mace': {dmg:'1d6', type:'bludgeoning'},
  'Quarterstaff': {dmg:'1d6', type:'bludgeoning'},
  'Sickle': {dmg:'1d4', type:'slashing', finesse:true},
  'Spear': {dmg:'1d6', type:'piercing'},
  'Light Crossbow': {dmg:'1d8', type:'piercing', ranged:true},
  'Dart': {dmg:'1d4', type:'piercing', finesse:true, ranged:true},
  'Shortbow': {dmg:'1d6', type:'piercing', ranged:true},
  'Sling': {dmg:'1d4', type:'bludgeoning', ranged:true}
};

const MARTIAL_WEAPONS = {
  'Longsword': {dmg:'1d8', type:'slashing'},
  'Shortsword': {dmg:'1d6', type:'piercing', finesse:true},
  'Rapier': {dmg:'1d8', type:'piercing', finesse:true},
  'Warhammer': {dmg:'1d8', type:'bludgeoning'},
  'Battleaxe': {dmg:'1d8', type:'slashing'},
  'Greatsword': {dmg:'2d6', type:'slashing'},
  'Halberd': {dmg:'1d10', type:'slashing'}
};
