// Auto-generated by file split — part of the D&D 5e Character Sheet project
// Edit this file directly to add or modify playable races/species.

const RACES = {
  vedalken: {
    name: 'Vedalken',
    speed: '30 ft',
    asi: {int:2, wis:1},
    numRacialLanguages: 1,
    skillChoice: {options:['Arcana','History','Investigation','Medicine','Performance','Sleight of Hand'], label:'Tireless Precision skill'},
    features: [
      "Vedalken Dispassion: Advantage on Intelligence, Wisdom, and Charisma saving throws.",
      "Tireless Precision: Proficient in {SKILL} and {TOOL}. When you make an ability check with either, roll a d4 and add it to the total (a rolled bonus — apply it yourself at the table).",
      "Partially Amphibious: You can breathe underwater for up to 1 hour per long rest.",
      "Ability Score Increase: +2 Intelligence, +1 Wisdom (already applied to your modifiers above)."
    ]
  }
};
